## DataManipulation with Numpy

Numpy- Numerical Python-npy
- Developed by Travis Oliphant in 2005
- Arrays
    - one dimension array
    - two dimension array
    - Multi dimension arry
- Linear algebra, Fourier Transforms,materics

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy

In [4]:
numpy.__version__

'1.18.1'

In [5]:
import numpy as np

In [7]:
np.__version__

'1.18.1'

In [9]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

## creating array
- we 2 possibilities
    - list
    - Tuples

In [11]:
#help(np.array)

### Zero Dimension Arry

In [15]:
x=np.array(8)
print(x)
print(type(x))
print(np.ndim(x))# tell you dimension of x

8
<class 'numpy.ndarray'>
0


## 1-Dimensional Array

In [16]:
x1=[3,6,9,5]
print(x1,type(x1))

[3, 6, 9, 5] <class 'list'>


In [17]:
arr=np.array(x1)
print(arr,type(arr))

[3 6 9 5] <class 'numpy.ndarray'>


In [19]:
arr1=np.array([5,3,8,9,2,66])
print(arr1,type(arr1))
print(np.ndim(arr1))

[ 5  3  8  9  2 66] <class 'numpy.ndarray'>
1


In [21]:
# no of elements in array
np.size(arr1)

6

In [22]:
#no of rows and no of columns
np.shape(arr1) 

(6,)

In [23]:
arr1

array([ 5,  3,  8,  9,  2, 66])

## 2-Dimensional Arry

In [31]:
arr2=np.array([[1,2,3],[3,2,55],[5,6,7]])
print(arr2)
print("dim:",np.ndim(arr2))
print("size:",np.size(arr2))
print("shape:",np.shape(arr2))
print("type:",type(arr2))

[[ 1  2  3]
 [ 3  2 55]
 [ 5  6  7]]
dim: 2
size: 9
shape: (3, 3)
type: <class 'numpy.ndarray'>


## 3-Dimensional Array

In [34]:
arr3=np.array([[[1,6,9,3],[3,5,22,34]]])
print(arr3)
print(type(arr3))
print(np.ndim(arr3))


[[[ 1  6  9  3]
  [ 3  5 22 34]]]
<class 'numpy.ndarray'>
3


In [35]:
# find out shape and size
print(np.shape(arr3))

(1, 2, 4)


In [36]:
np.size(arr3)

8

## Accessing elements in nd array
- Index
    - +ve index [starts with 0]
    - -ve index [starts with -1]
- Slicling[Start:stop:step]
    - start value is included
    - stop value is excluded
    - the default step is 1
- loop
    - for

In [41]:
arr1

array([ 5,  3,  8,  9,  2, 66])

In [43]:
arr1[3]

9

In [44]:
arr1[-3]

9

In [46]:
arr1[1:5]

array([3, 8, 9, 2])

In [48]:
arr1[::2]# even index postional elements

array([5, 8, 2])

In [49]:
arr1[1::2]

array([ 3,  9, 66])

In [50]:
arr1

array([ 5,  3,  8,  9,  2, 66])

In [51]:
arr2

array([[ 1,  2,  3],
       [ 3,  2, 55],
       [ 5,  6,  7]])

In [52]:
np.shape(arr2)

(3, 3)

In [53]:
# row index starts as 0
# column index starts with 0

In [57]:
arr2[2]

array([5, 6, 7])

In [61]:
arr2[:,0]

array([1, 3, 5])

In [62]:
arr2

array([[ 1,  2,  3],
       [ 3,  2, 55],
       [ 5,  6,  7]])

In [64]:
arr2[0::2]# accessing 0th row and last row

array([[1, 2, 3],
       [5, 6, 7]])

In [66]:
arr2[0:3:2]#accessing oth row and 2 nd row

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
# accessing the 0th column and last column
print(arr2)
arr2[:,0:3:2]# rows,columns

[[ 1  2  3]
 [ 3  2 55]
 [ 5  6  7]]


array([[ 1,  3],
       [ 3, 55],
       [ 5,  7]])

In [84]:
arr2[1,1]# 1-row index,1-column index

2

In [85]:
arr2[2][0]

5

In [86]:
arr2[2,0]

5

In [87]:
arr2[1:3,1:3]

array([[ 2, 55],
       [ 6,  7]])

# Accessing elements in 3-Dimensional Array

In [91]:
arr3

array([[[ 1,  6,  9,  3],
        [ 3,  5, 22, 34]]])

In [92]:
np.shape(arr3)

(1, 2, 4)

In [113]:
arr3[0:,:,0]

array([[1, 3]])

In [115]:
arr3[0:,:,0:3:2]

array([[[ 1,  9],
        [ 3, 22]]])

In [116]:
arr3

array([[[ 1,  6,  9,  3],
        [ 3,  5, 22, 34]]])

In [117]:
arr3[0:,1,2]

array([22])

In [129]:
for i in arr3:
    for j in i:
        for k in j:
            print(k)

1
6
9
3
3
5
22
34


## math method

In [130]:
dir(np.math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [132]:
np.math.pi

3.141592653589793

In [134]:
x=np.math.pi/2
print(x)
np.sin(x)

1.5707963267948966


1.0

In [135]:
np.sin(90)

0.8939966636005579

In [136]:
np.sin(1)

0.8414709848078965

In [139]:
np.cos(90)

-0.4480736161291701

In [142]:
np.tan(90)## sin(90)/cos(90)==1/0

-1.995200412208242

In [143]:
np.math.log(2)

0.6931471805599453

In [144]:
help(np.math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [145]:
np.math.remainder(5,2)

1.0

In [148]:
np.math.floor(2.3)

2

In [149]:
np.sinh(90)

6.102016471589204e+38

In [152]:
np.math.acos(1)

0.0