In [1]:
import numpy as np

### Creating array with different methods
- array
- Zeros
- ones
- linspace
- logspace
- arange
- random

In [6]:
z=np.zeros(3)
z

array([0., 0., 0.])

In [9]:
z=np.zeros((3,2),dtype="int")
z

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
a=np.ones((1,4,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
#help(np.linspace)

In [15]:
d=np.linspace(1,10,21)
d

array([ 1.  ,  1.45,  1.9 ,  2.35,  2.8 ,  3.25,  3.7 ,  4.15,  4.6 ,
        5.05,  5.5 ,  5.95,  6.4 ,  6.85,  7.3 ,  7.75,  8.2 ,  8.65,
        9.1 ,  9.55, 10.  ])

In [19]:
x=np.logspace(1,10,8)
x

array([1.00000000e+01, 1.93069773e+02, 3.72759372e+03, 7.19685673e+04,
       1.38949549e+06, 2.68269580e+07, 5.17947468e+08, 1.00000000e+10])

In [21]:
#help(np.arange)

In [23]:
ar1=np.arange(3)
ar1

array([0, 1, 2])

In [24]:
ar1=np.arange(1,10,2)
ar1

array([1, 3, 5, 7, 9])

In [32]:
ar2=np.arange(10,1,-2)
print(ar2)
print(np.ndim(ar2))
np.shape(ar2)

[10  8  6  4  2]
1


(5,)

## Random
    - np.random
- random
- randint
- rand
- shfful

In [33]:
from numpy import random

In [34]:
from numpy import *

In [35]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bit_generator',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',

In [36]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [42]:
r1=np.random.random() ## [0.0 -1.0]
r1

0.4169096007276871

In [44]:
r2=np.random.random((2))
r2


array([0.75304032, 0.07471159])

In [46]:
r2=np.random.random((2,3))
r2


array([[0.38089856, 0.54575002, 0.37336233],
       [0.75854878, 0.86795293, 0.79196245]])

In [56]:
#help(np.random.randint)
r3=np.random.randint(2) # low=2 
r3

1

In [66]:
r3=np.random.randint(2,10,size=(2,6)) # low=2 
r3

array([[3, 6, 2, 9, 2, 2],
       [3, 9, 9, 3, 5, 5]])

In [68]:
r4=np.random.rand(2,3)
r4

array([[0.35462374, 0.8518343 , 0.9833466 ],
       [0.95283891, 0.16334374, 0.64289743]])

In [75]:
r41=np.random.random((2,6))
r41

array([[0.64533338, 0.7515035 , 0.17741724, 0.29968095, 0.58173822,
        0.78316179],
       [0.9108499 , 0.12400035, 0.94813644, 0.72051864, 0.63305789,
        0.92604965]])

### converting or Re-shapeing

In [77]:
ar1=np.arange(1,9)
ar1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
#help(np.reshape)

In [80]:
ar2=ar1.reshape(2,4)
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
ar2=np.reshape(ar1,(4,2))
ar2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [82]:
g=ar1.reshape(2,3)
g

ValueError: cannot reshape array of size 8 into shape (2,3)

In [85]:
ar3=ar1.reshape(1,8,1)
ar3

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]]])

In [98]:
## converting 2D into 1D
new_ar1=ar2.reshape(8,)
print(new_ar1)
print(np.ndim(new_ar1))
print(type(new_ar1))

[1 2 3 4 5 6 7 8]
1
<class 'numpy.ndarray'>


In [94]:
a=ar2.flatten()
print(a)
np.ndim(a)


[1 2 3 4 5 6 7 8]


1

## Filtering

In [102]:
x=np.array([3,5,6,22])
y=[True,False,True,False]
a=x[y]
print(a)

[3 6]


In [103]:
arr=np.array([56,34,23,12])
f=[]
for i in arr:
    if i>30:
        f.append(True)
    else:
        f.append(False)
new_arr=arr[f]
print(f)
print(new_arr)

[True, True, False, False]
[56 34]


In [104]:
arr[arr>30]

array([56, 34])

## Saving Data

In [108]:
x=np.random.randint(1,10,(4,3))
x

array([[2, 4, 3],
       [4, 9, 7],
       [3, 7, 5],
       [6, 9, 9]])

In [109]:
ar1=np.save("ar1",x)

## loading the npy file into jupyter

In [110]:
lo=np.load("ar1.npy")
lo

array([[2, 4, 3],
       [4, 9, 7],
       [3, 7, 5],
       [6, 9, 9]])

## Statistics & Aggregation Functions

In [112]:
x

array([[2, 4, 3],
       [4, 9, 7],
       [3, 7, 5],
       [6, 9, 9]])

In [113]:
x.sum()

68

In [115]:
#help(np.sum)

In [116]:
# axis=0-->columns
# axis=1-->row
x.sum(0)

array([15, 29, 24])

In [117]:
x.sum(axis=0)

array([15, 29, 24])

In [118]:
print(x.sum(axis=1))
print(x.sum(1))

[ 9 20 15 24]
[ 9 20 15 24]


In [119]:
x.mean()

5.666666666666667

In [120]:
print("mean of rows:",x.mean(axis=1))
print("mean of columns:",x.mean(axis=0))

mean of rows: [3.         6.66666667 5.         8.        ]
mean of columns: [3.75 7.25 6.  ]


In [123]:
print(x)
print(x.min())

[[2 4 3]
 [4 9 7]
 [3 7 5]
 [6 9 9]]
2


In [124]:
x.max()

9

In [125]:
x.min(1)# min values of every row

array([2, 4, 3, 6])

In [126]:
x.min(0) # min values of every column

array([2, 4, 3])

In [127]:
x.argmin()# minimum element index

0

In [128]:
x.argmin(axis=1)# row of mimimum element index

array([0, 0, 0, 0], dtype=int64)

In [129]:
x.argmin(0) # column wise minimum element index

array([0, 0, 0], dtype=int64)

In [130]:
x.argmax(1)# row of maximum element index

array([1, 1, 1, 1], dtype=int64)

In [131]:
x.argmax(0)# columnwise of maximum element index

array([3, 1, 3], dtype=int64)

In [132]:
x

array([[2, 4, 3],
       [4, 9, 7],
       [3, 7, 5],
       [6, 9, 9]])

In [134]:
#help(np.std)

In [135]:
print("standard deviation of x:",x.std())

standard deviation of x: 2.4267032964268394


In [136]:
x.std(1)# std with rows

array([0.81649658, 2.05480467, 1.63299316, 1.41421356])

In [137]:
x.std(0)# std of columns

array([1.47901995, 2.04633819, 2.23606798])

In [139]:
#help(np.var)

In [140]:
x.var()

5.888888888888888

In [141]:
x.var(1)

array([0.66666667, 4.22222222, 2.66666667, 2.        ])

In [142]:
x.var(axis=0)

array([2.1875, 4.1875, 5.    ])

In [143]:
x.prod()# product of x

308629440

In [144]:
x.prod(axis=1)# product of rows wise elements

array([ 24, 252, 105, 486])

In [145]:
x.prod(axis=0)

array([ 144, 2268,  945])

In [146]:
x.cumsum()

array([ 2,  6,  9, 13, 22, 29, 32, 39, 44, 50, 59, 68], dtype=int32)

In [147]:
x

array([[2, 4, 3],
       [4, 9, 7],
       [3, 7, 5],
       [6, 9, 9]])

In [148]:
x.cumsum(1)

array([[ 2,  6,  9],
       [ 4, 13, 20],
       [ 3, 10, 15],
       [ 6, 15, 24]], dtype=int32)

In [149]:
x.cumsum(axis=0)

array([[ 2,  4,  3],
       [ 6, 13, 10],
       [ 9, 20, 15],
       [15, 29, 24]], dtype=int32)

In [150]:
x.cumprod()

array([        2,         8,        24,        96,       864,      6048,
           18144,    127008,    635040,   3810240,  34292160, 308629440],
      dtype=int32)

In [153]:
x.all()

True

In [154]:
x.any()

True

In [160]:
x.ptp()

7

In [161]:
np.median(x)

5.5

In [163]:
np.median(x,1)

array([3., 7., 5., 9.])

In [164]:
np.median(x,0)

array([3.5, 8. , 6. ])

In [165]:
np.average(x)

5.666666666666667

In [166]:
np.average(x,1)

array([3.        , 6.66666667, 5.        , 8.        ])

In [167]:
np.average(x,0)

array([3.75, 7.25, 6.  ])